import Link from 'next/link';
import { services } from '@/components/data';
import { Marquee, QuoteForm, Reveal, SectionHeading, Stat } from '@/components/Site';

const sectors = ['◒ Oil & Gas', '⚓ Maritime Transport', 'ϟ Power & Utilities', '☀ Solar Energy', '⌘ Engineering', '▣ Ports & Terminals'];
const highlights = [['Marine & Offshore', 'Vessels, crews and port calls coordinated with operational control.'], ['Technical Support', 'Specialist hands for inspection, integrity and field execution.'], ['Energy Solutions', 'Reliable power systems designed for demanding, remote sites.'], ['Procurement & Supply', 'Critical materials sourced, assured and delivered without delay.']];
const principles = [['Mission', 'Deliver safe, reliable marine and technical support that keeps critical operations moving.'], ['Vision', 'Set the regional standard for dependable, integrated offshore service delivery.'], ['Core Values', 'Safety-led decisions, transparent partnerships and ownership at every handover.']];
const leaders = [['Adebayo Akinyemi', 'Managing Director', 'Sets strategic direction and builds trusted client partnerships around dependable delivery.'], ['Ifeoma Okoro', 'Director, Operations', 'Turns complex schedules into safe, coordinated field execution across every workfront.'], ['Tunde Alabi', 'Director, Technical', 'Guides technical assurance, engineering quality and practical asset-integrity solutions.']];
const stats = [['30+', 'Yrs Maritime Expertise', 'anchor'], ['0', 'LTI Recordable Incidents', 'shield'], ['100%', 'Vessel Fleet Coverage', 'ship'], ['100%', 'JQS Certified Partner', 'certificate']] as const;

function StatIcon({ name }: { name: typeof stats[number][2] }) { const common = { width: 20, height: 20, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 1.8, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const, 'aria-hidden': true }; if (name === 'anchor') return <svg {...common}><circle cx="12" cy="5" r="2.5"/><path d="M12 7.5V21M5 12H2.5a9.5 9.5 0 0 0 19 0H19M5 16.5 12 21l7-4.5M9 10h6"/></svg>; if (name === 'shield') return <svg {...common}><path d="M12 3 19 6v5c0 4.7-3 8-7 10-4-2-7-5.3-7-10V6l7-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></svg>; if (name === 'ship') return <svg {...common}><path d="M4 15h16l-2 4H6l-2-4ZM7 15V8h10v7M10 8V5h4v3M3 21c1.2-1 2.5-1 3.7 0 1.2-1 2.5-1 3.7 0 1.2-1 2.5-1 3.7 0 1.2-1 2.5-1 3.7 0"/></svg>; return <svg {...common}><path d="M7 3h10v11H7zM9 7h6M9 10h4M9 19l3-2 3 2v-4H9z"/></svg>; }

export default function Home() { return <>
  <section className="hero-grid relative isolate min-h-[580px] overflow-hidden px-5 pb-14 pt-32 text-white sm:min-h-[680px] sm:pt-40"><div className="hero-orbit"/><div className="relative mx-auto max-w-7xl"><p className="eyebrow text-[10px] sm:text-xs">◆ TASOL MARINE SERVICES LTD ◆ LIGHTHOUSE</p><h1 className="mt-4 max-w-4xl text-[32px] font-black leading-[1.02] tracking-[-.04em] sm:text-5xl md:text-7xl">Marine, Energy & Technical Services Built for <span className="heading-accent">Complex Operations</span></h1><p className="mt-5 max-w-2xl text-[15px] leading-6 text-white/75 sm:text-lg sm:leading-8">Assured capability, dependable people and operational discipline for high-stakes environments.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:max-w-xl"><Link href="/services" className="focus-ring flex min-h-12 items-center justify-center rounded bg-cyan px-3 text-center text-sm font-bold text-navy transition hover:bg-white active:scale-[.98] sm:px-6 sm:text-base">Explore Our Services</Link><Link href="/contact" className="focus-ring flex min-h-12 items-center justify-center rounded border border-white/60 px-3 text-center text-sm font-bold transition hover:border-cyan hover:text-cyan active:scale-[.98] sm:px-6 sm:text-base">Contact Headquarters</Link></div></div></section>
  <section className="bg-navy px-5 py-6 text-white sm:py-8"><div className="mx-auto grid max-w-5xl grid-cols-2 gap-3 sm:gap-4">{stats.map(([value, label, icon]) => <Stat key={label} value={value} label={label} icon={<StatIcon name={icon}/>}/>)}</div></section>
  <section className="mx-auto grid max-w-7xl gap-8 px-5 py-14 sm:py-20 lg:grid-cols-2 lg:py-24"><Reveal><SectionHeading eyebrow="Executive Statement" title="Built for the operations others find" accent="difficult." copy="TASOL brings disciplined delivery to marine, energy and technical work where safety, uptime and trust cannot be compromised."/></Reveal><div className="grid gap-3 sm:grid-cols-2">{highlights.map(([title, copy], i) => <Reveal key={title} className="interactive-card rounded-xl border border-slate-200 bg-white p-4 sm:p-5"><span className="text-sm font-black text-cyan">0{i + 1}</span><h3 className="mt-2 font-bold text-navy">{title}</h3><p className="mt-2 text-sm leading-5 text-slate-500">{copy}</p></Reveal>)}</div></section>
  <section className="bg-slate-50 px-5 py-14 sm:py-20"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2 lg:gap-12"><Reveal className="relative min-h-64 overflow-hidden rounded-2xl bg-cover bg-center sm:min-h-80" ><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:"linear-gradient(rgba(11,30,60,.12),rgba(11,30,60,.12)),url('https://images.unsplash.com/photo-1559825481-12a05cc00344?auto=format&fit=crop&w=1200&q=80')"}}/><div className="absolute bottom-4 left-4 rounded bg-navy p-4 text-sm text-white"><b className="text-cyan">ZERO HARM</b><p>Policy-led execution</p></div></Reveal><div><SectionHeading eyebrow="About TASOL" title="A Lagos-based partner with global" accent="operational standards."/><div className="mt-6 grid gap-3 sm:grid-cols-3">{principles.map(([title, copy]) => <div key={title} className="rounded bg-white p-4 shadow-sm"><b className="text-navy">{title}</b><p className="mt-2 text-sm leading-5 text-slate-500">{copy}</p></div>)}</div><Link href="/about" className="focus-ring mt-6 inline-flex min-h-11 items-center font-bold text-cyan">Discover our story →</Link></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-14 sm:py-20"><SectionHeading eyebrow="Operational Capability" title="Engineered services for every critical" accent="phase."/><div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([slug, name, bullets], i) => <Reveal key={slug} className="interactive-card rounded-xl border border-slate-100 bg-white p-5 shadow-md"><span className="text-sm font-black text-cyan">0{i + 1}</span><h3 className="mt-2 text-lg font-bold text-navy">{name}</h3><ul className="my-3 space-y-1 text-sm text-slate-500">{bullets.map(b => <li key={b}>• {b}</li>)}</ul><Link href={'/services/' + slug} className="focus-ring inline-flex min-h-11 items-center font-bold text-cyan">Explore Service Details →</Link></Reveal>)}</div></section>
  <section className="bg-navy px-5 py-14 text-white sm:py-20"><div className="mx-auto max-w-7xl"><SectionHeading light eyebrow="Target Sectors" title="Operational domains we" accent="understand."/><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sectors.map(x => <div key={x} className="interactive-card rounded border border-white/15 p-4 font-bold">{x}</div>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-14 sm:py-20"><SectionHeading eyebrow="Leadership & Directorate" title="Decisive leadership," accent="accountable delivery."/><div className="mt-7 grid gap-4 md:grid-cols-3">{leaders.map(([name, role, bio], i) => <Reveal className="interactive-card overflow-hidden rounded-xl border" key={name}><div className="h-40 bg-slate-200 bg-cover sm:h-52" style={{backgroundImage:`url(https://images.unsplash.com/photo-${i === 1 ? '1573496359142-b8d87734a5a2' : '1560250097-0b93528c311a'}?auto=format&fit=crop&w=700&q=75)`}}/><div className="p-5"><b className="text-navy">{name}</b><p className="text-sm text-cyan">{role}</p><p className="mt-2 text-sm leading-5 text-slate-500">{bio}</p><Link href={'/leadership/' + ['adebayo-akinyemi', 'ifeoma-okoro', 'tunde-alabi'][i]} className="focus-ring mt-3 inline-flex min-h-11 items-center font-bold text-cyan">Executive Profile →</Link></div></Reveal>)}</div></section>
  <section className="ocean px-5 py-14 text-white sm:py-20"><Reveal className="mx-auto max-w-7xl"><p className="eyebrow text-[10px]">STRATEGIC EDGE</p><h2 className="mt-3 text-[28px] font-black leading-tight tracking-tight sm:text-4xl">High-stakes operations, managed with <span className="heading-accent">certainty.</span></h2><div className="mt-7 grid gap-3 sm:grid-cols-2 md:grid-cols-5">{['Safety-led culture', 'Local expertise', 'Integrated delivery', 'Rapid mobilisation', 'Transparent reporting'].map(x => <p className="border-l-2 border-cyan pl-3 text-sm" key={x}>✓ {x}</p>)}</div></Reveal></section>
  <section className="bg-slate-50 px-5 py-14 sm:py-20"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Safety Is Fundamental" title="Performance without" accent="compromise."/><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['0.00 Lost Time Injury Rate', '100% Certified Crew Onboard', '24/7 HSE Monitoring', '100% Incident Review'].map(x => <Reveal key={x} className="rounded bg-white p-4 font-bold text-navy shadow-sm">{x}</Reveal>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-14 sm:py-20"><SectionHeading eyebrow="Recent Engagements" title="Capability demonstrated in the" accent="field."/><div className="mt-7 grid gap-3 md:grid-cols-4">{['Offshore logistics', 'Subsea integrity', 'Port support', 'Solar deployment'].map((x, i) => <Link href={'/projects/' + ['delta-logistics', 'subsea-inspection', 'port-mobilisation', 'solar-power'][i]} className="focus-ring interactive-card relative flex h-40 items-start overflow-hidden rounded-xl bg-slate-700 p-4 text-white sm:h-56" key={x}><span className="rounded bg-cyan px-2 py-1 text-xs text-navy">{x}</span><b className="absolute bottom-4 left-4">View project →</b></Link>)}</div></section>
  <Marquee/><section className="bg-cyan px-5 py-12 sm:py-16"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-2"><div><h2 className="text-[28px] font-black leading-tight tracking-tight text-navy sm:text-4xl">Let&apos;s Support Your Next Marine <span className="heading-accent">Operation</span></h2><p className="mt-3">Speak with our operations team: +234 (0) 1 700 2480</p></div><Link href="/contact" className="focus-ring flex min-h-12 items-center justify-center self-center rounded bg-navy px-6 text-center font-bold text-white transition hover:bg-ink active:scale-[.98]">Request a Quote</Link></div></section>
  <section className="bg-slate-100 px-5 py-14 sm:py-20"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><SectionHeading eyebrow="Registered Headquarters" title="Start the" accent="conversation." copy="Tell us about the technical tender, project scope or operational requirement."/><QuoteForm/></div></section>
</>; }
