import Link from 'next/link';
import { services } from '@/components/data';
import { CountUp, Marquee, QuoteForm, Reveal, SectionHeading } from '@/components/Site';

const sectors = ['◒ Oil & Gas', '⚓ Maritime Transport', 'ϟ Power & Utilities', '☀ Solar Energy', '⌘ Engineering', '▣ Ports & Terminals'];
const capabilities = [['Marine & Offshore', 'Vessel, port and offshore logistics coordinated without compromise.'], ['Technical Support', 'Practical engineering expertise for uptime-critical assets.'], ['Energy Solutions', 'Resilient power and solar systems tailored to site conditions.'], ['Procurement & Supply', 'Trusted sourcing that keeps remote projects moving.']];
const principles = [['Mission', 'Deliver safe, dependable support when operations cannot pause.'], ['Vision', 'Be West Africa’s most trusted partner for complex operations.'], ['Core Values', 'Act with integrity, readiness and measurable accountability.']];
const leaders = [['Adebayo Akinyemi', 'Managing Director', 'Sets the operational vision and accountable partnerships behind every engagement.'], ['Ifeoma Okoro', 'Director, Operations', 'Turns complex field requirements into coordinated, safe delivery plans.'], ['Tunde Alabi', 'Director, Technical', 'Leads asset integrity and engineering decisions that protect uptime.']];

export default function Home() { return <>
  <section className="hero-grid relative min-h-[620px] overflow-hidden px-5 pb-16 pt-32 text-white sm:px-6 sm:pt-36 md:min-h-[680px] md:pt-44"><div className="hero-orbit"/><div className="relative mx-auto max-w-7xl"><Reveal><p className="text-[10px] font-bold tracking-[.18em] text-cyan sm:text-xs">◆ TASOL MARINE SERVICES LTD ◆ LIGHTHOUSE</p><h1 className="mt-4 max-w-4xl text-[2rem] font-black leading-[.98] tracking-[-.045em] sm:text-4xl md:text-6xl lg:text-7xl">Marine, Energy & Technical Services Built for Complex Operations</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/75 sm:text-lg sm:leading-8">Assured capability, dependable people and operational discipline for high-stakes environments.</p><div className="mt-7 flex flex-col gap-3 min-[420px]:flex-row"><Link href="/services" className="focus-ring inline-flex min-h-12 items-center justify-center rounded bg-cyan px-5 font-bold text-navy transition hover:bg-white active:scale-[.98]">Explore Our Services</Link><Link href="/contact" className="focus-ring inline-flex min-h-12 items-center justify-center rounded border border-white/60 px-5 font-bold transition hover:border-cyan hover:text-cyan active:scale-[.98]">Contact Headquarters</Link></div></Reveal></div></section>
  <section className="bg-navy px-5 py-6 text-white sm:px-6"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-x-4 gap-y-5 lg:grid-cols-4">{[[30, '+', 'Yrs Maritime Expertise'], [0, '', 'LTI Recordable Incidents'], [100, '%', 'Vessel Fleet Coverage'], [0, 'NOGIC', 'JQS Certified Partner']].map(([value, suffix, label], index) => <Reveal key={String(label)}><div className="border-l border-cyan pl-3"><b className="text-2xl text-cyan sm:text-3xl">{index === 3 ? suffix : <CountUp value={value as number} suffix={suffix as string}/>}</b><p className="mt-1 text-xs leading-4 text-white/75">{label}</p></div></Reveal>)}</div></section>
  <section className="mx-auto grid max-w-7xl gap-8 px-5 py-14 sm:px-6 sm:py-20 lg:grid-cols-2 lg:gap-12"><Reveal><SectionHeading eyebrow="Executive Statement" title="Built for the operations others find difficult." copy="TASOL brings disciplined delivery to marine, energy and technical work where safety, uptime and trust cannot be compromised."/></Reveal><div className="grid gap-3 sm:grid-cols-2">{capabilities.map(([title, copy], index) => <Reveal key={title}><article className="interactive-card h-full rounded-xl border border-slate-200 bg-white p-5"><span className="text-xs font-black text-cyan">0{index + 1}</span><h3 className="mt-2 font-bold text-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></article></Reveal>)}</div></section>
  <section className="bg-slate-50 px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2 lg:gap-12"><Reveal><div className="relative min-h-64 overflow-hidden rounded-2xl bg-cover bg-center sm:min-h-80" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1559825481-12a05cc00344?auto=format&fit=crop&w=1200&q=80')" }}><div className="absolute bottom-4 left-4 rounded bg-navy p-4 text-white"><b className="text-xs text-cyan">ZERO HARM</b><p className="text-sm">Policy-led execution</p></div></div></Reveal><Reveal><SectionHeading eyebrow="About TASOL" title="A Lagos-based partner with global operational standards."/><div className="mt-6 grid gap-3 sm:grid-cols-3">{principles.map(([title, copy]) => <div key={title} className="rounded-xl bg-white p-4 shadow-sm"><b className="text-sm text-navy">{title}</b><p className="mt-2 text-xs leading-5 text-slate-500">{copy}</p></div>)}</div><Link href="/about" className="focus-ring mt-6 inline-flex min-h-11 items-center font-bold text-cyan hover:text-navy">Discover our story →</Link></Reveal></div></section>
  <section className="mx-auto max-w-7xl px-5 py-14 sm:px-6 sm:py-20"><Reveal><SectionHeading eyebrow="Operational Capability" title="Engineered services for every critical phase."/></Reveal><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(([slug, name, bullets], index) => <Reveal key={slug}><Link href={`/services/${slug}`} className="interactive-card focus-ring block h-full rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><span className="text-xs font-black text-cyan">0{index + 1}</span><h3 className="mt-2 text-lg font-bold text-navy">{name}</h3><ul className="my-3 space-y-1 text-sm leading-6 text-slate-500">{bullets.map(bullet => <li key={bullet}>• {bullet}</li>)}</ul><span className="text-sm font-bold text-cyan">Explore Service Details →</span></Link></Reveal>)}</div></section>
  <section className="ocean px-5 py-14 text-white sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><Reveal><SectionHeading eyebrow="Target Sectors" title="Operational domains we understand."/></Reveal><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sectors.map(sector => <Reveal key={sector}><div className="rounded-lg border border-white/15 p-4 text-sm font-bold">{sector}</div></Reveal>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-14 sm:px-6 sm:py-20"><Reveal><SectionHeading eyebrow="Leadership & Directorate" title="Decisive leadership, accountable delivery."/></Reveal><div className="mt-8 grid gap-5 md:grid-cols-3">{leaders.map(([name, role, copy], index) => <Reveal key={name}><article className="interactive-card overflow-hidden rounded-xl border bg-white"><div className="h-44 bg-slate-200 bg-cover bg-center sm:h-52" style={{ backgroundImage: `url(https://images.unsplash.com/photo-${index === 1 ? '1573496359142-b8d87734a5a2' : '1560250097-0b93528c311a'}?auto=format&fit=crop&w=700&q=75)` }}/><div className="p-5"><b className="text-navy">{name}</b><p className="text-sm text-cyan">{role}</p><p className="mt-3 text-sm leading-6 text-slate-500">{copy}</p><Link href={`/leadership/${name.toLowerCase().replaceAll(' ', '-')}`} className="focus-ring mt-4 inline-flex min-h-10 items-center text-sm font-bold text-cyan">Executive Profile →</Link></div></article></Reveal>)}</div></section>
  <section className="bg-slate-50 px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><Reveal><SectionHeading eyebrow="Recent Engagements" title="Capability demonstrated in the field."/></Reveal><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Offshore logistics', 'Subsea integrity', 'Port support', 'Solar deployment'].map((project, index) => <Link href={`/projects/${['delta-logistics','subsea-inspection','port-mobilisation','solar-power'][index]}`} className="interactive-card focus-ring relative flex h-44 items-end overflow-hidden rounded-xl bg-slate-700 p-4 text-white sm:h-56" key={project}><span className="rounded bg-cyan px-2 py-1 text-xs text-navy">{project}</span><b className="absolute bottom-4 right-4 text-sm">View project →</b></Link>)}</div></div></section>
  <Marquee/>
  <section className="bg-cyan px-5 py-12 sm:px-6 sm:py-16"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-2"><div><h2 className="text-3xl font-black leading-tight tracking-[-.035em] text-navy sm:text-4xl">Let&apos;s Support Your Next Marine Operation</h2><p className="mt-3 text-sm sm:text-base">Speak with our operations team: +234 (0) 1 700 2480</p></div><Link href="/contact" className="focus-ring inline-flex min-h-12 items-center justify-center self-center rounded bg-navy px-6 text-center font-bold text-white transition hover:bg-white hover:text-navy active:scale-[.98]">Request a Quote</Link></div></section>
  <section className="bg-slate-100 px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2 lg:gap-10"><Reveal><SectionHeading eyebrow="Registered Headquarters" title="Start the conversation." copy="Tell us about the technical tender, project scope or operational requirement."/></Reveal><Reveal><QuoteForm/></Reveal></div></section>
</>; }
