'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useInView } from 'framer-motion';
import { services, nav } from '@/components/data';

export { services };

type IconName = 'anchor' | 'shield-check' | 'ship' | 'certificate' | 'target' | 'telescope' | 'droplet' | 'bolt' | 'sun' | 'settings' | 'clock-check' | 'clipboard-check' | 'building' | 'mail' | 'arrow-right' | 'check';
export function Icon({ name, size = 19 }: { name: IconName, size?: number }) {
  const props = { width: size, height: size, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 1.8, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const, 'aria-hidden': true };
  const paths: Record<IconName, React.ReactNode> = {
    anchor: <><circle cx="12" cy="5" r="2.5"/><path d="M12 7.5V21M5 12H2.5a9.5 9.5 0 0 0 19 0H19M5 16.5 12 21l7-4.5M9 10h6"/></>,
    'shield-check': <><path d="M12 3 19 6v5c0 4.7-3 8-7 10-4-2-7-5.3-7-10V6l7-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,
    ship: <><path d="M4 15h16l-2 4H6l-2-4ZM7 15V8h10v7M10 8V5h4v3M3 21c1.2-1 2.5-1 3.7 0 1.2-1 2.5-1 3.7 0 1.2-1 2.5-1 3.7 0 1.2-1 2.5-1 3.7 0"/></>,
    certificate: <><circle cx="12" cy="10" r="4"/><path d="M8.8 12.4 8 21l4-2 4 2-.8-8.6M7 4h10"/></>, target: <><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="m16.5 7.5 4-4M17 3.5h3.5V7"/></>, telescope: <><path d="m5 9 11-3 2 6-11 3-2-6ZM13 14l2 6M8 15l-2 5M4 20h14M17 8l2-2"/></>,
    droplet: <path d="M12 3s-6 6.7-6 11a6 6 0 0 0 12 0c0-4.3-6-11-6-11Z"/>, bolt: <path d="m13 2-9 12h7l-1 8 9-12h-7l1-8Z"/>, sun: <><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.12 2.12-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V20.3h-3v-.08A1.7 1.7 0 0 0 10.68 18.66a1.7 1.7 0 0 0-1.88.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 7.02 15a1.7 1.7 0 0 0-1.56-1.03h-.08v-3h.08A1.7 1.7 0 0 0 7.02 9.94a1.7 1.7 0 0 0-.34-1.88l-.06-.06L8.74 5.88l.06.06a1.7 1.7 0 0 0 1.88.34 1.7 1.7 0 0 0 1.03-1.56v-.08h3v.08a1.7 1.7 0 0 0 1.03 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06L19.8 8l-.06.06a1.7 1.7 0 0 0-.34 1.88 1.7 1.7 0 0 0 1.56 1.03h.08v3h-.08A1.7 1.7 0 0 0 19.4 15Z"/></>,
    'clock-check': <><circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2M8.5 17l1.5 1.5 3.5-3.5"/></>, 'clipboard-check': <><path d="M8 4h8M9 3h6v3H9zM6 6h12v15H6z"/><path d="m9 14 2 2 4-4"/></>, building: <path d="M4 21V4a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1v17M2 21h20M8 7h2m-2 4h2m-2 4h2m6-6h2m-2 4h2m-2 4h2"/>, mail: <><rect x="3" y="5" width="18" height="14" rx="1"/><path d="m4 7 8 6 8-6"/></>,
    'arrow-right': <path d="M5 12h14M13 6l6 6-6 6"/>, check: <path d="m5 12 4 4L19 6"/>
  };
  return <svg {...props}>{paths[name]}</svg>;
}
export function IconBadge({ name }: { name: IconName }) { return <span className="icon-badge"><Icon name={name}/></span>; }
export function CheckList({ items }: { items: string[] }) { return <ul className="mt-4 space-y-2 text-sm leading-6 text-slate-600">{items.map(item => <li key={item} className="flex gap-2"><span className="mt-1 shrink-0 text-cyan"><Icon name="check" size={15}/></span>{item}</li>)}</ul>; }
export function PageHero({ eyebrow, title, accent, copy }: { eyebrow: string, title: string, accent?: string, copy?: string }) { return <section className="hero-grid page-hero text-white"><div className="mx-auto max-w-7xl"><p className="eyebrow text-[10.5px]">◆ TASOL MARINE SERVICES LTD ◆ {eyebrow}</p><h1 className="hero-heading mt-[10px] max-w-4xl text-[30px] sm:text-5xl">{title}{accent && <> <span className="heading-accent">{accent}</span></>}</h1>{copy && <p className="mt-[10px] max-w-2xl text-[15px] leading-6 text-white/75 sm:text-base">{copy}</p>}</div></section>; }

export function Header() {
  const path = usePathname(); const [open, setOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [small, setSmall] = useState(false); const searchInput = useRef<HTMLInputElement>(null);
  useEffect(() => { const onScroll = () => setSmall(window.scrollY > 20); onScroll(); addEventListener('scroll', onScroll); return () => removeEventListener('scroll', onScroll); }, []);
  useEffect(() => { document.body.style.overflow = open ? 'hidden' : ''; return () => { document.body.style.overflow = ''; }; }, [open]);
  useEffect(() => { if (searchOpen) searchInput.current?.focus(); }, [searchOpen]);
  const linkClass = (href: string) => `nav-link focus-ring ${path === href ? 'text-cyan' : 'text-white/80 hover:text-white'}`;
  return <header className={`fixed top-0 z-50 w-full border-b border-white/10 transition-all ${small ? 'bg-navy/95 shadow-xl' : 'bg-navy/75'} backdrop-blur-md`}>
    <div className={`mx-auto flex max-w-7xl items-center justify-between px-4 transition-all sm:px-5 ${small ? 'h-16' : 'h-[68px] md:h-20'}`}>
      <Link href="/" className="focus-ring text-base font-black tracking-[.18em] text-white sm:text-lg">TASOL<span className="text-cyan">.</span></Link>
      <div className="relative flex items-center gap-[18px]">
        <AnimatePresence initial={false}>{searchOpen && <motion.form role="search" aria-label="Site search" className="absolute right-0 top-1/2 flex w-[min(72vw,340px)] -translate-y-1/2 items-center rounded-md border border-white/20 bg-navy p-1 shadow-xl sm:w-[340px]" initial={{ opacity: 0, x: 24 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 24 }} transition={{ duration: .18 }} onSubmit={e => e.preventDefault()}>
          <label htmlFor="site-search" className="sr-only">Search TASOL</label><input ref={searchInput} id="site-search" type="search" placeholder="Search TASOL..." className="focus-ring min-w-0 flex-1 bg-transparent px-3 py-2 text-sm text-white placeholder:text-white/55"/>
          <button type="button" aria-label="Close search" onClick={() => setSearchOpen(false)} className="focus-ring grid h-11 w-11 shrink-0 place-items-center rounded text-white transition hover:text-cyan"><CloseIcon/></button>
        </motion.form>}</AnimatePresence>
        <nav aria-label="Quick navigation" className="flex items-center">
          <Link href="/" aria-label="Home" className="focus-ring grid h-11 w-11 shrink-0 place-items-center rounded-md text-[rgba(255,255,255,0.55)] transition hover:text-white"><HomeIcon/></Link>
          <Link href="/about" aria-label="About" className="focus-ring hidden h-11 w-11 shrink-0 place-items-center rounded-md text-[rgba(255,255,255,0.55)] transition hover:text-white min-[400px]:grid"><BuildingIcon/></Link>
          <Link href="/contact" aria-label="Contact" className="focus-ring grid h-11 w-11 shrink-0 place-items-center rounded-md text-[rgba(255,255,255,0.55)] transition hover:text-white"><MailIcon/></Link>
        </nav>
        <span aria-hidden="true" className="h-4 w-px shrink-0 bg-[rgba(255,255,255,0.15)]"/>
        <div className="flex items-center">
          <button aria-label="Open search" aria-expanded={searchOpen} onClick={() => setSearchOpen(true)} className="focus-ring grid h-11 w-11 shrink-0 place-items-center rounded-md text-white transition hover:text-cyan"><SearchIcon/></button>
          <button aria-label="Open menu" aria-expanded={open} onClick={() => setOpen(true)} className="focus-ring grid h-11 w-11 shrink-0 place-items-center rounded-md border border-white/15 text-white transition hover:border-cyan hover:text-cyan"><MenuIcon/></button>
        </div>
      </div>
    </div>
    <AnimatePresence>{open && <><motion.button aria-label="Close navigation menu" className="fixed inset-0 top-[68px] z-[-1] w-full bg-ink/65 md:top-20" onClick={() => setOpen(false)} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} />
      <motion.aside aria-label="Navigation menu" className="fixed right-0 top-0 h-dvh w-[min(88vw,380px)] bg-ink px-6 pt-5 shadow-2xl" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', damping: 28, stiffness: 280 }}>
        <div className="flex items-center justify-between"><b className="text-lg tracking-[.18em] text-white">TASOL<span className="text-cyan">.</span></b><button aria-label="Close menu" onClick={() => setOpen(false)} className="focus-ring grid h-11 w-11 place-items-center rounded-md border border-white/15 text-2xl text-white">×</button></div>
        <p className="eyebrow mt-10 text-[10px]">Explore TASOL</p>
        <nav className="mt-3">{nav.map(([href, name], i) => <motion.div key={href} initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .1 + i * .06 }}><Link onClick={() => setOpen(false)} href={href} className={linkClass(href) + ' flex w-full border-b border-white/10 text-sm hover:border-cyan'}>{name}</Link></motion.div>)}</nav>
        <Link href="/contact" onClick={() => setOpen(false)} className="focus-ring mt-7 flex min-h-12 items-center justify-center rounded-md bg-cyan px-5 text-sm font-black text-navy">Request a Quote</Link>
      </motion.aside></>}</AnimatePresence>
  </header>;
}

function HomeIcon() { return <svg aria-hidden="true" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/></svg>; }
function BuildingIcon() { return <svg aria-hidden="true" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M4 21V4a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1v17M2 21h20M8 7h2m-2 4h2m-2 4h2m6-6h2m-2 4h2m-2 4h2"/></svg>; }
function MailIcon() { return <svg aria-hidden="true" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="14" rx="1"/><path d="m4 7 8 6 8-6"/></svg>; }
function SearchIcon() { return <svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.25" strokeLinecap="round"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.5 4.5"/></svg>; }
function CloseIcon() { return <svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.25" strokeLinecap="round"><path d="m6 6 12 12M18 6 6 18"/></svg>; }
function MenuIcon() { return <svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.25" strokeLinecap="round"><path d="M4 7h16M4 12h16M4 17h16"/></svg>; }

export function Reveal({ children, className = '' }: { children: React.ReactNode, className?: string }) { return <motion.div initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .48, ease: 'easeOut' }} className={className}>{children}</motion.div>; }
export function SectionHeading({ eyebrow, title, accent, copy, light = false }: { eyebrow: string, title: string, accent?: string, copy?: string, light?: boolean }) { return <div className="max-w-2xl"><p className="eyebrow mb-2 text-[10px] sm:text-xs">◆ TASOL MARINE SERVICES LTD ◆ {eyebrow}</p><h2 className={`text-[28px] sm:text-4xl md:text-5xl ${light ? 'text-white' : 'text-navy'}`}>{title}{accent && <> <span className="heading-accent">{accent}</span></>}</h2>{copy && <p className={`mt-4 text-[15px] leading-6 sm:text-base sm:leading-7 ${light ? 'text-white/70' : 'text-slate-600'}`}>{copy}</p>}</div>; }

export function Stat({ value, label, icon }: { value: string, label: string, icon: React.ReactNode }) { const ref = useRef<HTMLDivElement>(null); const inView = useInView(ref, { once: true, amount: .6 }); const n = Number(value.replace(/\D/g, '')); const suffix = value.replace(/[\d.]/g, ''); return <div ref={ref} className="flex items-center gap-[14px] rounded-[10px] border border-white/10 bg-white/[.05] p-4"><div className="grid h-[34px] w-[34px] shrink-0 place-items-center rounded-[8px] bg-cyan/15 text-cyan">{icon}</div><div><motion.b className="block text-[17px] font-bold leading-[1.1] tracking-tight text-white" initial={{ opacity: 0 }} animate={inView ? { opacity: 1 } : {}}>{inView ? <Counter to={n} suffix={suffix} /> : '0'}</motion.b><p className="mt-[2px] text-[10.5px] leading-[1.3] text-[#8fa3b5]">{label}</p></div></div>; }
function Counter({ to, suffix }: { to: number, suffix: string }) { const [value, setValue] = useState(0); useEffect(() => { let start = 0; const duration = 900; let frame = 0; const tick = (t: number) => { if (!start) start = t; const progress = Math.min((t - start) / duration, 1); setValue(Math.round(to * (1 - Math.pow(1 - progress, 3)))); if (progress < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [to]); return <>{value}{suffix}</>; }

export function Chatbot() { const [open, setOpen] = useState(false), [question, setQuestion] = useState(''), [reply, setReply] = useState('Welcome to TASOL. How can we support your operation?'); async function ask(e: React.FormEvent) { e.preventDefault(); if (!question) return; const r = await fetch('/api/chat', { method: 'POST', body: JSON.stringify({ question }) }); setReply((await r.json()).answer); setQuestion(''); } return <><button aria-label="Open TASOL assistant" onClick={() => setOpen(!open)} className="focus-ring fixed bottom-4 right-4 z-40 grid h-12 w-12 place-items-center rounded-full bg-cyan text-lg text-navy shadow-2xl sm:bottom-5 sm:right-5 sm:h-14 sm:w-14">◌</button>{open && <section className="fixed bottom-20 right-4 z-40 w-[calc(100%-2rem)] max-w-sm rounded-xl bg-white p-5 shadow-2xl"><b className="text-navy">TASOL Operations Desk</b><p className="mt-3 min-h-12 text-sm text-slate-600">{reply}</p><form onSubmit={ask} className="mt-4 flex gap-2"><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask about services..." className="focus-ring min-w-0 flex-1 rounded border p-2 text-sm"/><button className="focus-ring min-h-11 rounded bg-navy px-3 text-white">→</button></form></section>}</>; }
export function Footer() { return <footer className="bg-ink px-5 py-10 text-white sm:py-14"><div className="mx-auto grid max-w-7xl gap-8 sm:grid-cols-2 md:grid-cols-4"><div><b className="text-xl tracking-widest">TASOL<span className="text-cyan">.</span></b><p className="mt-3 text-sm leading-6 text-slate-400">Marine, energy and technical services built for complex operations across West Africa.</p></div><div><b>Company</b><p className="mt-3 text-sm leading-7 text-slate-400">About Us<br/>Leadership<br/>HSE</p></div><div><b>Services</b><p className="mt-3 text-sm leading-7 text-slate-400">Marine & Maritime<br/>Engineering & Subsea<br/>Supply Chain</p></div><div><b>Headquarters</b><p className="mt-3 text-sm leading-7 text-slate-400">Lagos, Nigeria<br/>+234 (0) 1 700 2480<br/>operations@tasolmarine.com</p></div></div><p className="mx-auto mt-10 max-w-7xl border-t border-white/10 pt-5 text-xs text-slate-500">© 2026 TASOL Marine Services Ltd. All rights reserved.</p></footer>; }
export function Marquee({ label = 'Partners & Clients' }: { label?: string }) { const logos = ['NOGIC JQS', 'Chevron', 'TotalEnergies', 'NLNG', 'NIMASA', 'Shell']; return <section className="overflow-hidden bg-slate-50 py-8 sm:py-10"><p className="mb-5 text-center text-[10px] font-bold uppercase tracking-[.18em] text-slate-500 sm:text-xs">Trusted by {label}</p><div className="marquee"><div className="marquee-track">{[...logos, ...logos].map((x, i) => <div aria-hidden={i >= logos.length} key={i} className="grid h-14 w-32 shrink-0 place-items-center rounded bg-white text-sm font-bold text-slate-400 shadow-sm sm:h-16 sm:w-40">{x}</div>)}</div></div></section>; }
export function QuoteForm({ full = false }: { full?: boolean }) { const [sent, setSent] = useState(false); async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = Object.fromEntries(new FormData(e.currentTarget)); await fetch('/api/quotes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); setSent(true); } return <form onSubmit={submit} className="grid gap-3 rounded-xl bg-white p-4 shadow-xl sm:p-5 md:grid-cols-2">{['fullName', 'email', 'company', 'phone'].map(x => <input required key={x} name={x} placeholder={x === 'fullName' ? 'Full name' : x === 'email' ? 'Official email' : x === 'company' ? 'Company / organization' : 'Phone number'} type={x === 'email' ? 'email' : 'text'} className="focus-ring min-h-11 rounded border border-slate-200 px-3"/>)}<select required name="service" className="focus-ring min-h-11 rounded border border-slate-200 px-3"><option value="">Service category</option>{services.map(s => <option key={s[0]}>{s[1]}</option>)}</select><textarea required name="message" placeholder={full ? 'Project scope & timeline' : 'How can we help?'} className="focus-ring min-h-28 rounded border border-slate-200 p-3 md:col-span-2"/><button className="focus-ring min-h-12 rounded bg-cyan px-5 font-bold text-navy transition hover:bg-navy hover:text-white active:scale-[.98]">{sent ? 'Request received — thank you' : 'Request Technical Support →'}</button></form>; }
